<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_Lupa Password_ico_chevron_up_minor</name>
   <tag></tag>
   <elementGuidId>3faee9f7-5a24-488e-9d11-3ee6bd978fa0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>svg.ico_chevron_up_minor</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Lupa Password?'])[1]/following::*[name()='svg'][4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>2ea720e3-7103-412e-80a8-e7a1f8c60da5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>1dcad920-6887-445b-bfe5-827f8dd8227a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>e28c520c-92e2-4426-910d-9c3a328480b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 20 20</value>
      <webElementGuid>e6893980-0d5e-4df1-9740-bdf89e7658a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>#2E2E2E</value>
      <webElementGuid>3e3244e6-ef28-4ea0-a926-9ea26c3880e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>7ae7094d-546a-49fb-8752-fd91695b99be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ico_chevron_up_minor</value>
      <webElementGuid>42a2b86a-50fc-4eb7-9012-75e9ea6edb6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TFAJS-1661481019304&quot;)/section[1]/div[@class=&quot;bl-modal p-24&quot;]/div[@class=&quot;bl-modal__wrapper&quot;]/div[@class=&quot;bl-card&quot;]/div[@class=&quot;bl-modal__body&quot;]/div[@class=&quot;p-24&quot;]/div[1]/div[@class=&quot;tfa-method-wrapper&quot;]/div[@class=&quot;mt-12&quot;]/div[@class=&quot;bl-flex-container other-method-wrapper justify-space-between&quot;]/div[@class=&quot;bl-flex-item&quot;]/svg[@class=&quot;ico_chevron_up_minor&quot;]</value>
      <webElementGuid>2420180b-5374-432d-927d-60b24738d416</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lupa Password?'])[1]/following::*[name()='svg'][4]</value>
      <webElementGuid>17f2cbf9-665b-4c22-99d5-072ccec58052</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar'])[1]/following::*[name()='svg'][5]</value>
      <webElementGuid>a5076a7b-71f9-4195-894d-882c6b0549b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
