<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>4f9f2410-2e4f-4630-ab60-0b9cc23905d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='homepage-home-section-app']/section/div/div/div/div/div/div/div[5]/a/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9611ece1-6f20-4719-b506-9137f552243d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://s2.bukalapak.com/dope/1581555568239/original/hp_menu_icon_b3f21cd5-db80-468e-8209-db5fdfa6a694.jpg</value>
      <webElementGuid>0b2a4b13-09d4-4252-a5c1-82cf8cdd1527</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Bukalapak</value>
      <webElementGuid>f9defbd2-188c-4eb1-99b4-a26a41bf2501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;homepage-home-section-app&quot;)/section[@class=&quot;bl-section dope-section mt-48&quot;]/div[@class=&quot;bl-container&quot;]/div[@class=&quot;qa-dope-container bl-dope-container&quot;]/div[@class=&quot;bl-dope-container__wrapper&quot;]/div[@class=&quot;bl-dope-container__head&quot;]/div[@class=&quot;bl-dope-container__head-content&quot;]/div[@class=&quot;bl-flex-container mb-0 bl-dope-container__grid-wrapper&quot;]/div[@class=&quot;bl-flex-item mt-16 mb-16 bl-dope-container__grid-item&quot;]/a[@class=&quot;bl-dope-item bl-dope-item--medium&quot;]/div[@class=&quot;bl-dope-item__body&quot;]/img[1]</value>
      <webElementGuid>fbbe18ad-ded7-43cd-a028-867b4a481e65</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='homepage-home-section-app']/section/div/div/div/div/div/div/div[5]/a/div/img</value>
      <webElementGuid>8986f097-e648-49e0-9548-11e501068df2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Bukalapak'])[5]</value>
      <webElementGuid>fdf0dce7-73b3-48bf-bfe2-007364ef5bd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/a/div/img</value>
      <webElementGuid>e9e907da-9e18-47c6-a254-2b6aa631b682</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://s2.bukalapak.com/dope/1581555568239/original/hp_menu_icon_b3f21cd5-db80-468e-8209-db5fdfa6a694.jpg' and @alt = 'Bukalapak']</value>
      <webElementGuid>27ad47a6-acfe-4908-aa50-aed42ce92c98</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
